<a href="https://colab.research.google.com/github/WhiteBeyond/AI/blob/main/AI_20_3_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
pip install -U scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.9/dist-packages (1.2.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.22.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.1.1)

In [98]:
from sklearn.linear_model import Perceptron
x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]

In [99]:
model = Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [100]:
x1  = [[0.5,0.5],[-0.3,-0.5],[10,2.3],[-1,-2]]
y1 = model.predict(x1)
print(y1)

[1 0 1 0]

In [101]:
x2 = [[-0.5,-0.5],[-0.5,0.5],[0.5,-0.5],[-0.5,1]]
t2 = [1,1,0,0]
model = Perceptron()
model.fit(x2,t)
model.score(x2,t)

1.0

In [102]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
x = iris.data
y = iris.target
print(x[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]

In [103]:
X_train ,X_test , Y_train, Y_test = train_test_split(x, y, test_size = 0.3)
sc = StandardScaler()
sc.fit(X_train)
x_train_std = sc.transform(X_train)
x_test_std = sc.transform(X_test)
print(x_train_std[:5], X_train[:5])
model = Perceptron(max_iter=40, eta0=0.1, random_state=0)
model.fit(x_train_std, Y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(Y_test)
print('độ chính xác mô hình:', accuracy_score(Y_test, y_pred))

[[ 2.13380729  1.79262285  1.61977516  1.23376092]
 [ 2.13380729 -0.08963114  1.27444238  1.3663555 ]
 [-0.95981666  1.79262285 -1.31555343 -1.41813052]
 [ 1.77685068 -0.56019464  1.27444238  0.83597721]
 [-0.12691791 -0.56019464  0.69888776  1.49895007]] [[7.7 3.8 6.7 2.2]
 [7.7 3.  6.1 2.3]
 [5.1 3.8 1.6 0.2]
 [7.4 2.8 6.1 1.9]
 [5.8 2.8 5.1 2.4]]
[0 0 0 1 0 2 2 1 0 1 2 2 2 2 0 2 1 0 0 1 0 0 2 2 1 0 0 1 1 1 1 1 2 1 2 0 0
 0 2 0 0 0 1 1 1]
[0 0 0 1 0 2 2 1 0 2 2 2 2 2 0 1 1 0 0 1 0 0 2 2 1 0 0 1 1 1 1 1 2 1 2 0 0
 0 2 0 0 0 1 1 1]
độ chính xác mô hình: 0.9555555555555556

In [104]:
import pandas as pd
data = pd.read_csv('crabs.csv')
#thay thế
#6 đặc tính + loài => giới tính

data["speies"].replace({"B": "0", "O": "1"}, inplace=True) #M=0 O=1
data["sex"].replace({"F": "0", "M": "1"}, inplace=True)
data.head(50)

   speies sex  index  fontallip  rearwidth  length  width  depth
0       0   1      1        8.1        6.7    16.1   19.0    7.0
1       0   1      2        8.8        7.7    18.1   20.8    7.4
2       0   1      3        9.2        7.8    19.0   22.4    7.7
3       0   1      4        9.6        7.9    20.1   23.1    8.2
4       0   1      5        9.8        8.0    20.3   23.0    8.2
5       0   1      6       10.8        9.0    23.0   26.5    9.8
6       0   1      7       11.1        9.9    23.8   27.1    9.8
7       0   1      8       11.6        9.1    24.5   28.4   10.4
8       0   1      9       11.8        9.6    24.2   27.8    9.7
9       0   1     10       11.8       10.5    25.2   29.3   10.3
10      0   1     11       12.2       10.8    27.3   31.6   10.9
11      0   1     12       12.3       11.0    26.8   31.5   11.4
12      0   1     13       12.6       10.0    27.7   31.7   11.4
13      0   1     14       12.8       10.2    27.2   31.8   10.9
14      0   1     15       12.8       10.9    27.4   31.5   11.0
15      0   1     16       12.9       11.0    26.8   30.9   11.4
16      0   1     17       13.1       10.6    28.2   32.3   11.0
17      0   1     18       13.1       10.9    28.3   32.4   11.2
18      0   1     19       13.3       11.1    27.8   32.3   11.3
19      0   1     20       13.9       11.1    29.2   33.3   12.1
20      0   1     21       14.3       11.6    31.3   35.5   12.7
21      0   1     22       14.6       11.3    31.9   36.4   13.7
22      0   1     23       15.0       10.9    31.4   36.4   13.2
23      0   1     24       15.0       11.5    32.4   37.0   13.4
24      0   1     25       15.0       11.9    32.5   37.2   13.6
25      0   1     26       15.2       12.1    32.3   36.7   13.6
26      0   1     27       15.4       11.8    33.0   37.5   13.6
27      0   1     28       15.7       12.6    35.8   40.3   14.5
28      0   1     29       15.9       12.7    34.0   38.9   14.2
29      0   1     30       16.1       11.6    33.8   39.0   14.4
30      0   1     31       16.1       12.8    34.9   40.7   15.7
31      0   1     32       16.2       13.3    36.0   41.7   15.4
32      0   1     33       16.3       12.7    35.6   40.9   14.9
33      0   1     34       16.4       13.0    35.7   41.8   15.2
34      0   1     35       16.6       13.5    38.1   43.4   14.9
35      0   1     36       16.8       12.8    36.2   41.8   14.9
36      0   1     37       16.9       13.2    37.3   42.7   15.6
37      0   1     38       17.1       12.6    36.4   42.0   15.1
38      0   1     39       17.1       12.7    36.7   41.9   15.6
39      0   1     40       17.2       13.5    37.6   43.9   16.1
40      0   1     41       17.7       13.6    38.7   44.5   16.0
41      0   1     42       17.9       14.1    39.7   44.6   16.8
42      0   1     43       18.0       13.7    39.2   44.4   16.2
43      0   1     44       18.8       15.8    42.1   49.0   17.8
44      0   1     45       19.3       13.5    41.6   47.4   17.8
45      0   1     46       19.3       13.8    40.9   46.5   16.8
46      0   1     47       19.7       15.3    41.9   48.5   17.8
47      0   1     48       19.8       14.2    43.2   49.7   18.6
48      0   1     49       19.8       14.3    42.4   48.9   18.3
49      0   1     50       21.3       15.7    47.1   54.6   20.0

In [116]:
yy = data["sex"].values.tolist()
data.drop('sex', axis = 1).head()
xx = []
for  index, rows in data.iterrows(): 
  list =[rows.speies, rows.fontallip, rows.rearwidth, rows.length, rows.width, rows.depth]
  xx.append(list)

In [117]:
X_train ,X_test , Y_train, Y_test = train_test_split(xx, yy, test_size = 0.3)
sc = StandardScaler()
sc.fit(X_train)
x_train_std = sc.transform(X_train)
x_test_std = sc.transform(X_test)
model = Perceptron(max_iter=40, eta0=0.1, random_state=0)
model.fit(x_train_std, Y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(Y_test)
print('độ chính xác mô hình:', accuracy_score(Y_test, y_pred))

['1' '1' '0' '1' '1' '1' '1' '0' '1' '1' '0' '0' '0' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '0' '1' '0' '0' '1' '0' '1' '0' '1' '0' '0' '1' '0' '0'
 '0' '1' '1' '1' '1' '1' '1' '0' '1' '0' '1' '1' '1' '0' '0' '0' '1' '1'
 '0' '0' '1' '0' '0' '1']
['0', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '0', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0', '0', '1', '0', '1', '0', '1', '0', '0', '1', '0', '0', '0', '0', '1', '1', '1', '1', '1', '0', '1', '0', '1', '1', '1', '0', '0', '0', '1', '1', '0', '0', '1', '0', '0', '1']
độ chính xác mô hình: 0.95